#!/bin/bash

# Check if $PYFILE is set
if [ -z "$PYFILE" ]; then
  echo "Error: Environment variable \$PYFILE is not set."
  exit 1
fi

# Compile the Python script
python -m py_compile "$PYFILE"

# Rename the compiled bytecode file
compiled_file="${PYFILE}c"
mv "__pycache__/$compiled_file" "$compiled_file"

# Cleanup the temporary "__pycache__" directory
rm -rf "__pycache__"

